blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/voycelabs/bun-env/blob/develop/README.md
    about: Please review the project documentation before submitting an issue
  - name: Security Vulnerability
    url: https://github.com/voycelabs/bun-env/security/advisories/new
    about: Report security vulnerabilities through GitHub Security Advisories
